- name: add rabbitmq key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add rabbitmq repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install rabbitmq
  sudo: yes
  apt: pkg=rabbitmq-server state=latest

- name: create /etc/rabbitmq
  sudo: yes
  file: path=/etc/rabbitmq state=directory

- name: create rabbitmq config
  sudo: yes
  template: src=rabbitmq.config.tpl dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq
  when: apache_version.stdout.find('Apache/2.4.') != -1

- name: enable management console
  notify: restart rabbitmq
  rabbitmq_plugin: names=rabbitmq_management state=enabled